networks:
  kong-net:
    external: true

services:
  next:
    image: hadesgod/next-docker-workshop
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - kong-net
  hono:
    image: hadesgod/hono-docker-workshop
    environment:
      NODE_ENV: production
    ports:
      - 3333:3333
    networks:
      - kong-net
    restart: unless-stopped # [!code ++]
    healthcheck: # [!code ++]
      test: ["CMD-SHELL", "curl -f http://localhost:3333/healthz || exit 1"] # [!code ++]
      interval: 30s # [!code ++]
      timeout: 10s # [!code ++]
      retries: 3 # [!code ++]
      start_period: 10s # [!code ++]
  react:
    image: hadesgod/react-docker-workshop
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    networks:
      - kong-net
