networks:
  kong-net:
    external: true

services:
  next:
    image: next
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - kong-net
  hono:
    image: hono
    environment:
      NODE_ENV: production
    ports:
      - 3333:3333
    networks:
      - kong-net
  react:
    image: react
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    networks:
      - kong-net
